[build]
  # No build command needed for static HTML
  command = ""
  # Publish the frontend directory
  publish = "frontend"

# Optional: Add redirects if needed
# [[redirects]]
#   from = "/api/*"
#   to = "https://web-production-c1082.up.railway.app//api/:splat"
#   status = 200

[build.environment]
  # No Python environment needed for static site
  
# Optional: Set headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"