[metadata]
language = "python"
workDir = "backend"

[phases.setup]
# Install Python + system deps + all pip packages at build time
nixPkgs = [
  "python312.withPackages(ps: with ps; [flask flask-cors openai PyPDF2 python-dotenv pdf2image pytesseract Pillow gunicorn httpx])",
  "poppler",
  "tesseract"
]

[start]
# gunicorn is available globally
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
