[metadata]
language = "python"
workDir = "backend"

[phases.setup]
nixPkgs = ["python312", "poppler", "tesseract"]

[start]
# Option 1: activate venv first
cmd = ". /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"

# Option 2: direct path (alternative)
# cmd = "/opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"
