[metadata]
language = "python"
workDir = "backend"

[phases.setup]
nixPkgs = ["python312", "poppler", "tesseract"]

# Install pip and dependencies globally
commands = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
