[build]
  builder = "nixpacks"
  buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
  startCommand = "cd backend && gunicorn app:app"
  restartPolicyType = "on_failure"

[env]
  PORT = "8080"