[build]
  builder = "nixpacks"
  buildCommand = "cd rag-epr-2025 && pip install -r requirements.txt"

[deploy]
  startCommand = "cd rag-epr-2025 && gunicorn app:app"
  restartPolicyType = "on_failure"

[env]
  PORT = "8080"